workflows:
  react-native-workflow:
    name: React Native Workflow
    environment:
      node: latest
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Build Android App
        script: |
          cd android
          ./gradlew app:assembleRelease
      - name: Build iOS App
        script: |
          cd ios
          pod install
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
      - ios/build/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
